POST http://localhost:8081/realms/kaservice/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=kaservice_client&client_secret=KCzv6vHTwcQLdFH387A1oXTfEFm8vor8&username=u.userov@example.com&password=password&grant_type=password